name: Build and Deploy

on:
  push:
    branches:
      - test2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install -f

      # - name: Build Angular App
      #   run: npm run build -- --prod

  # deploy:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Installer APT
  #       run: sudo apt-get update && sudo apt-get install -y apt

  #     - name: Build Docker Image
  #       run: docker build -t bouhlelrochdi/mini-projet-devops-lab03:$GITHUB_SHA .

  #     - name: Login to Docker Hub
  #       # run: echo dckr_pat_nQ15v5jnU09JdVw3IV6XmL4uOjU | docker login -u bouhlelrochdi --password-stdin
  #       uses: docker/login-action@v2
  #       with:
  #         username: bouhlelrochdi
  #         password: dckr_pat_nQ15v5jnU09JdVw3IV6XmL4uOjU

  #     - name: Push Docker Image to Docker Hub
  #       run: docker push bouhlelrochdi/mini-projet-devops-lab03:latest

  docker:
    runs-on: ubuntu-latest
    steps:
# setup qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

# setup buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

# login to docker hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bouhlelrochdi
          password: dckr_pat_nQ15v5jnU09JdVw3IV6XmL4uOjU

# check
      - name: Check
        run: actions/checkout@v3

# build and push
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bouhlelrochdi/mini-projet-devops-lab03:latest
